# Generated by Django 5.1.6 on 2025-03-22 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_allergies_userprofile_current_weight_and_more"),
        ("workouts", "0002_exercise_alter_workoutplan_target_group_subplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="selected_sub_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workouts.subplan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selected_workout_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workouts.workoutplan",
            ),
        ),
    ]
