# Generated by Django 5.1.6 on 2025-04-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("popular", "Popular"),
                    ("completed", "Completed"),
                ],
                default="upcoming",
                max_length=100,
            ),
        ),
    ]
