# Generated by Django 5.1.6 on 2025-04-01 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_fitnessevent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessevent",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
