# Generated by Django 5.1.6 on 2025-04-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_fitnessevent_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessevent",
            name="end_time",
        ),
    ]
