# Generated by Django 5.1.6 on 2025-04-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_eventsubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventSubscription",
        ),
    ]
