# Generated by Django 5.1.6 on 2025-04-09 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_delete_eventsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessevent",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
