# Generated by Django 5.1.6 on 2025-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=200),
        ),
    ]
