# Generated by Django 5.1.6 on 2025-03-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendedDailyIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Average Adult", max_length=100)),
                ("calories", models.FloatField(default=2000.0)),
                ("protein", models.FloatField(default=50.0)),
                ("total_fat", models.FloatField(default=70.0)),
                ("saturated_fat", models.FloatField(default=20.0)),
                ("trans_fat", models.FloatField(default=2.0)),
                ("carbohydrates", models.FloatField(default=260.0)),
                ("fiber", models.FloatField(default=25.0)),
                ("sugars", models.FloatField(default=50.0)),
                ("cholesterol", models.FloatField(default=300.0)),
                ("sodium", models.FloatField(default=2300.0)),
                ("potassium", models.FloatField(default=3500.0)),
                ("vitamin_a", models.FloatField(default=900.0)),
                ("vitamin_c", models.FloatField(default=90.0)),
                ("vitamin_b", models.FloatField(default=1.3)),
                ("vitamin_d", models.FloatField(default=600.0)),
                ("calcium", models.FloatField(default=1000.0)),
                ("zinc", models.FloatField(default=11.0)),
            ],
        ),
        migrations.AddField(
            model_name="ingredient",
            name="calcium_per_unit",
            field=models.FloatField(default=0.0, help_text="Calcium per unit (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="carbohydrates_per_unit",
            field=models.FloatField(
                default=0.0, help_text="Total carbohydrates per unit (g)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="cholesterol_per_unit",
            field=models.FloatField(default=0.0, help_text="Cholesterol per unit (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fat_per_unit",
            field=models.FloatField(default=0.0, help_text="Total fat per unit (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fiber_per_unit",
            field=models.FloatField(
                default=0.0, help_text="Dietary fiber per unit (g)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="potassium_per_unit",
            field=models.FloatField(default=0.0, help_text="Potassium per unit (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="protein_per_unit",
            field=models.FloatField(default=0.0, help_text="Protein per unit (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="saturated_fat_per_unit",
            field=models.FloatField(
                default=0.0, help_text="Saturated fat per unit (g)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="sodium_per_unit",
            field=models.FloatField(default=0.0, help_text="Sodium per unit (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="sugars_per_unit",
            field=models.FloatField(default=0.0, help_text="Sugars per unit (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="trans_fat_per_unit",
            field=models.FloatField(default=0.0, help_text="Trans fat per unit (g)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_A_per_unit",
            field=models.FloatField(
                default=0.0, help_text="Vitamin A per unit (IU or mg)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_B_per_unit",
            field=models.FloatField(default=0.0, help_text="Vitamin B per unit (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_C_per_unit",
            field=models.FloatField(default=0.0, help_text="Vitamin C per unit (mg)"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="vitamin_D_per_unit",
            field=models.FloatField(
                default=0.0, help_text="Vitamin D per unit (IU or μg)"
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="zinc_per_unit",
            field=models.FloatField(default=0.0, help_text="Zinc per unit (mg)"),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_calcium",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_calories",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_carbohydrates",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_cholesterol",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_fat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_fiber",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_potassium",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_protein",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_saturated_fat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_sodium",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_sugars",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_trans_fat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_vitamin_A",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_vitamin_B",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_vitamin_C",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_vitamin_D",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="meal",
            name="dv_zinc",
            field=models.FloatField(default=0.0),
        ),
    ]
