# Generated by Django 5.1.6 on 2025-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cooking_instructions',
            field=models.TextField(default='Cooking instructions not provided yet.'),
        ),
    ]
