# Generated by Django 5.1.5 on 2025-02-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_cooking_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='duration',
            new_name='cooking_duration',
        ),
        migrations.AddField(
            model_name='meal',
            name='diet_type',
            field=models.CharField(choices=[('non-veg', 'Non-Vegetarian'), ('veg', 'Vegetarian'), ('vegan', 'Vegan')], default='non-veg', max_length=10),
        ),
    ]
