# Generated by Django 5.1.6 on 2025-03-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessgoal",
            name="category",
            field=models.CharField(
                choices=[
                    ("bmi_target", "BMI Target"),
                    ("weight_loss", "Weight Loss Target"),
                    ("muscle_gain", "Muscle Gain Target"),
                    ("endurance", "Endurance Training"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfitnessgoal",
            name="initial_value",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="userfitnessgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="not_started",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="userfitnessgoal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="UserFitnessProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="goals.userfitnessgoal",
                    ),
                ),
            ],
        ),
    ]
