# Generated by Django 5.1.6 on 2025-03-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_fitnessgoal_category_userfitnessgoal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='category',
            field=models.CharField(choices=[('bmi_target', 'BMI 目标值'), ('weight_loss', '减重目标值'), ('muscle_gain', '增肌目标值'), ('endurance', '耐力训练'), ('custom', '自定义')], default='custom', max_length=20),
        ),
    ]
