# Generated by Django 5.1.6 on 2025-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_fitnessgoal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitnessgoal',
            name='starting_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
