# Generated by Django 5.1.6 on 2025-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_userfitnessgoal_starting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitnessgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userfitnessgoal',
            name='starting_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
