# Generated by Django 5.1.6 on 2025-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_userfitnessgoal_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='category',
            field=models.CharField(choices=[('bmi_target', 'BMI Target'), ('weight_loss', 'Weight Loss Target'), ('muscle_gain', 'Muscle Gain Target'), ('endurance', 'Endurance Training'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
