# Generated by Django 5.1.6 on 2025-03-19 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_fitnessgoal_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfitnessgoal',
            old_name='starting_value',
            new_name='initial_value',
        ),
        migrations.CreateModel(
            name='UserFitnessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='goals.userfitnessgoal')),
            ],
        ),
    ]
