# Generated by Django 5.1.6 on 2025-03-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_rename_starting_value_userfitnessgoal_initial_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userfitnessgoal',
            name='initial_value',
        ),
        migrations.RemoveField(
            model_name='userfitnessgoal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userfitnessgoal',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='UserFitnessProgress',
        ),
    ]
