# Generated by Django 5.1.6 on 2025-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_remove_fitnessgoal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitnessgoal',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
    ]
