# Generated by Django 5.1.6 on 2025-04-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_dailycalorielog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycalorielog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailycalorielog',
            unique_together=set(),
        ),
    ]
