# Generated by Django 5.1.6 on 2025-04-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_remove_fitnessgoal_category_and_more"),
        ("goals", "0011_alter_dailycalorielog_options_and_more"),
    ]

    operations = []
