# Generated by Django 5.1.6 on 2025-04-04 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_alter_dailycalorielog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycalorielog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='userfitnessgoal',
            name='starting_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='dailycalorielog',
            unique_together={('user', 'date')},
        ),
    ]
