# Generated by Django 5.1.6 on 2025-04-04 22:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0012_merge_20250404_1749"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailycalorielog",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterUniqueTogether(
            name="dailycalorielog",
            unique_together={("user", "date")},
        ),
    ]
