# Generated by Django 5.1.6 on 2025-03-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_tag_alter_post_created_at_post_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
