# Generated by Django 5.1.6 on 2025-03-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
