# Generated by Django 5.1.6 on 2025-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("opening_hours", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("capacity", models.IntegerField()),
            ],
            options={
                "verbose_name": "Workout Plan",
                "verbose_name_plural": "Workout Plans",
                "db_table": "Workout Plans",
            },
        ),
    ]
