# Generated by Django 5.1.6 on 2025-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutplan",
            options={},
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="location",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="rating",
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="duration",
            field=models.CharField(default="4 Weeks", max_length=50),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="features",
            field=models.TextField(default="Standard workout plan features"),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="focus",
            field=models.TextField(default="General fitness and well-being"),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="schedule",
            field=models.TextField(default="Monday - Friday training"),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="target_group",
            field=models.CharField(default="General Fitness", max_length=255),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="workoutplan",
            table=None,
        ),
    ]
