# Generated by Django 5.1.6 on 2025-03-19 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("min", "Minutes"),
                            ("sets", "Sets"),
                            ("meters", "Meters"),
                            ("rounds", "Rounds"),
                        ],
                        default="sets",
                        max_length=10,
                    ),
                ),
                (
                    "calorie_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calories per unit (set/min/meter)",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="target_group",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="SubPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("focus", models.TextField()),
                ("schedule", models.TextField()),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_plans",
                        to="workouts.workoutplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubPlanExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_or_sets",
                    models.PositiveIntegerField(
                        help_text="Duration (minutes), sets, meters, or rounds"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.exercise",
                    ),
                ),
                (
                    "subplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.subplan",
                    ),
                ),
            ],
        ),
    ]
