# Generated by Django 5.1.6 on 2025-04-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_exercise_alter_workoutplan_target_group_subplan_and_more"),
        ("workouts", "0002_userworkoutselection"),
    ]

    operations = []
